function ff = createStemPlot(Y1)
%CREATEFIGURE(Y1)
%  Y1:  stem y

%  Auto-generated by MATLAB on 19-Jul-2012 12:44:56

% Create figure

figure2 = figure; %If open multiple plot, uncomment this line
%figure1=figure(2); %If do not want to open multiple plot,use this line

%set(figure1, 'Position', [550 500 700 300]) %big size
set(figure2, 'Position', [650 400 350 200]) %small size
% Create axes

% -90 to 90
axes1 = axes('Parent',figure2,...
    'XTickLabel',{'','-90','-60','-30','0','30','60','90'},...
    'XTick',[0 1 3 5 7 9 11 13]);


% axes1 = axes('Parent',figure2,... %try -120 to 120
%     'XTickLabel',{'','-120','-90','-60','-30','0','30','60','90','120'},...
%     'XTick',[0 1 3 5 7 9 11 13 15 17]);

view(axes1,[0 -90]);
box(axes1,'on');
hold(axes1,'all');

% Create stem
stem(Y1,'DisplayName','gain(1,1:13)');

% Create xlabel
xlabel({'Angee (deg.)'},'VerticalAlignment','cap',...
    'HorizontalAlignment','center');

% Create ylabel
ylabel({'RSSI (dBm)'},'VerticalAlignment','bottom','Rotation',90,...
    'HorizontalAlignment','center');

ff = figure2;